#!/bin/sh
#
# pwm_two_servos        Starts servos test program
#

[ -f /pwm_two_servos ] || exit 0

start() {
	echo "Starting script: "
        /pwm_two_servos --sleepMs 1 --updateStep 0.03  --enableLaser 4 --spiral 20 \
                        --servoYawFreq 1   --servoYawIP 0.25  --servoYawMaxValInNs 850000    --servoYawMinValInNs 650000 \
                        --servoPitchFreq 2 --servoPitchIP 0.0 --servoPitchMaxValInNs 1600000 --servoPitchMinValInNs 1400000 &
	echo "OK"
}
stop() {
	printf "Stopping script: "
	killall -SIGINT pwm_two_servos
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

