name: Compile examples for RV1103

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  prepare_host:
    runs-on: ubuntu-latest
    container: luckfoxtech/luckfox_pico:1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout SDK
        run: git clone https://github.com/LuckfoxTECH/luckfox-pico 
        
  build_on_container:
    runs-on: ubuntu-latest
    needs: prepare_host 
    container: 
      image: luckfoxtech/luckfox_pico:1.0
      options: --mount type=volume,source=luckfox-pico,target=/home
    steps:
      - name: Configure CMake
        run: ls -lR ${{github.workspace}} ; ls -lR $GITHUB_WORKSPACE ; ls -lR $GITHUB_WORKSPACE/..
        #cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}  ${{github.workspace}}/test_programs/hello_world # $GITHUB_WORKSPACE
