name: Compile examples for RV1103

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  prepare_container_and_build:
    strategy:
      matrix:
        build_type: [Release, Debug]
    runs-on: ubuntu-latest
    container: luckfoxtech/luckfox_pico:1.0
    env:
      ARCH: "arm"
      CROSS_COMPILE: "/build_env/tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin/"
      BUILD_TYPE: ${{ matrix.build_type }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout SDK
        run: git clone https://github.com/LuckfoxTECH/luckfox-pico.git /build_env

      - name: Build test programs
        run: |
             cmake -B  $GITHUB_WORKSPACE/build_${{env.BUILD_TYPE}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} $GITHUB_WORKSPACE/test_programs -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/build_${{env.BUILD_TYPE}}/install
             cmake --build $GITHUB_WORKSPACE/build_${{env.BUILD_TYPE}} --config ${{env.BUILD_TYPE}} --target install
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test_programs-${{ matrix.build_type }}
          path: |
            build_${{ matrix.build_type }}/install/bin/*
            build_${{ matrix.build_type }}/install/etc/init.d/*
