name: Compile examples for RV1103

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  prepare_container_and_build:
    runs-on: ubuntu-latest
    container: luckfoxtech/luckfox_pico:1.0
    env:
      ARCH: "arm"
      CROSS_COMPILE: "/build_env/tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin/"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout SDK
        run: git clone https://github.com/LuckfoxTECH/luckfox-pico.git /build_env

      - name: Cmake configure
        run: cmake -B  $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} $GITHUB_WORKSPACE/test_programs/hello_world

      - name: Build
        # Build your program with the given configuration
        run: cmake --build $GITHUB_WORKSPACE/build --config ${{env.BUILD_TYPE}}

      - name: dump
        run: |
          echo 'github.workspace === ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"
          ls -lR $GITHUB_WORKSPACE

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-rv1103-artifacts
          path: $GITHUB_WORKSPACE/build/hello_world

