name: Compile examples for RV1103

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  prepare_container_and_build:
    runs-on: ubuntu-latest
    container: luckfoxtech/luckfox_pico:1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout SDK
        run: git clone https://github.com/LuckfoxTECH/luckfox-pico /build_env
      - name: debug
        run: ls -lR / ; echo ${{github.workspace}} 
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}  ${{github.workspace}}/test_programs/hello_world
