name: Compile examples for RV1103

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  prepare_container_and_build:
    runs-on: ubuntu-latest
    container: luckfoxtech/luckfox_pico:1.0
    env:
      ARCH: "arm"
      CROSS_COMPILE: "/build_env/tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin/"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout SDK
        run: git clone https://github.com/LuckfoxTECH/luckfox-pico.git /build_env

      - name: Build test programs
        run: |
             cmake -B  $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} $GITHUB_WORKSPACE/test_programs
             cmake --build $GITHUB_WORKSPACE/build --config ${{env.BUILD_TYPE}}

      - name: Find executable test programs
        id: prepare
        run: |
          echo "executables=$(find $GITHUB_WORKSPACE/build -type f -executable -print | tr '\n' ',')" >> $GITHUB_ENV
          echo "executables=${executables%,}" >> $GITHUB_ENV # Remove the trailing comma

      - name: Publish Test Programs Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test_programs
          path: ${{ env.executables }}
