name: Compile examples for RV1103

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  prepare_container_and_build:
    runs-on: ubuntu-latest
    container: luckfoxtech/luckfox_pico:1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: dump
        run: |
          echo 'github.workspace === ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"
      - name: Checkout SDK
        run: |
             git clone https://github.com/LuckfoxTECH/luckfox-pico /build_env
             cmake -B  $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} $GITHUB_WORKSPACE/test_programs/hello_world
